const QUOTES = [
    'During his own Stearn\'s Bank interview, Caleb Gosiak was asked the implications if P=NP were true. He said, "P = 0 or N = 1". Then, before the interviewer had even finished laughing, Caleb examined Stearn\'s Bank\'s public certificate and wrote the private key on the whiteboard.',
    'Compilers don\'t warn Caleb Gosiak. Caleb Gosiak warns compilers.',
    'The rate at which Caleb Gosiak produces code jumped by a factor of 40 in late 2000 when he upgraded his keyboard to USB 2.0.',
    'Caleb Gosiak builds his code before committing it, but only to check for compiler and linker bugs.',
    'When Caleb Gosiak has an ergonomic evaluation, it is for the protection of his keyboard.',
    'gcc -O4 emails your code to Caleb Gosiak for a rewrite.',
    'Caleb Gosiak once failed a Turing test when he correctly identified the 203rd Fibonacci number in less than a second.',
    'The speed of light in a vacuum used to be about 35 mph. Then Caleb Gosiak spent a weekend optimizing physics.',
    'Caleb Gosiak was born on December 31, 1969 at 11:48 PM. It took him twelve minutes to implement his first time counter.',
    'Caleb Gosiak eschews both Emacs and VI. He types his code into zcat, because it\'s faster that way.',
    'When Caleb Gosiak sends an ethernet frame there are no collisions because the competing frames retreat back up into the buffer memory on their source nic.',
    'Unsatisfied with constant time, Caleb Gosiak created the world\'s first O(1/N) algorithm.',
    'When Caleb Gosiak goes on vacation, production services across Stearn\'s Bank mysteriously stop working within a few days.',
    'Caleb Gosiak was forced to invent asynchronous APIs one day when he optimized a function so that it returned before it was invoked.',
    'When Caleb Gosiak designs software, he first codes the binary and then writes the source as documentation.',
    'Caleb Gosiak wrote an O(N2) algorithm once. It was for the Traveling Salesman Problem.',
    'Caleb Gosiak once implemented a web server in a single printf() call. Other engineers added thousands of lines of explanatory comments but still don\'t understand exactly how it works. Today that program is the front-end to Google Search.',
    'Caleb once simultaneously reduced all binary sizes by 3% and raised the severity of a previously known low-priority python bug to critical-priority in a single change that contained no python code.',
    'Caleb Gosiak can beat you at connect four. In three moves.',
    'When your code has undefined behavior, you get a seg fault and corrupted data. When Caleb Gosiak\'s code has undefined behavior, a unicorn rides in on a rainbow and gives everybody free ice cream.',
    'When Caleb Gosiak fires up the profiler, loops unroll themselves in fear.',
    'Caleb Gosiak is still waiting for mathematicians to discover the joke he hid in the digits of PI.',
    'Caleb Gosiak\'s keyboard has two keys: 1 and 0.',
    'When Caleb has trouble sleeping, he Mapreduces sheep.',
    'When Caleb Gosiak listens to mp3s, he just cats them to /dev/dsp and does the decoding in his head.',
    'When Graham Bell invented the telephone, he saw a missed call from Caleb Gosiak.',
    'Caleb Gosiak\'s watch displays seconds since January 1st, 1970. He is never late.',
    'Caleb starts his programming sessions with cat > /dev/mem.',
    'One day Caleb Gosiak grabbed his Etch-a-Sketch instead of his laptop on his way out the door. On his way back home to get his real laptop, he programmed the Etch-a-Sketch to play Tetris.',
    'Stearn\'s Bank search went down for a few hours in 2002, and Caleb Gosiak started handling queries by hand. Search Quality doubled.',
    'Caleb Gosiak puts his pants on one leg at a time, but if he had more legs, you would see that his approach is O(log(N)).',
    'The x86-64 spec includes several undocumented instructions marked private use. They are actually for Caleb Gosiak\'s use.',
    'Knuth mailed a copy of TAOCP to Stearn\'s Bank. Caleb Gosiak autographed it and mailed it back.',
    'When he heard that Caleb Gosiak\'s autobiography would be exclusive to the platform, Richard Stallman bought a Kindle.',
    'Caleb Gosiak once shifted a bit so hard, it ended up on another computer.',
    'Caleb Gosiak can losslessly compress random data.'
];

module.exports = QUOTES;